//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 8/21/2012 11:47:15 PM
namespace ConferenceStarterKit.TechEdServiceReference
{
    
    /// <summary>
    /// There are no comments for ODataTEEntities in the schema.
    /// </summary>
    public partial class ODataTEEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ODataTEEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ODataTEEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("ODataTEModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("ConferenceStarterKit.TechEdServiceReference", typeName.Substring(12)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("ConferenceStarterKit.TechEdServiceReference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("ODataTEModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for AudienceCategories in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<AudienceCategory> AudienceCategories
        {
            get
            {
                if ((this._AudienceCategories == null))
                {
                    this._AudienceCategories = base.CreateQuery<AudienceCategory>("AudienceCategories");
                }
                return this._AudienceCategories;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<AudienceCategory> _AudienceCategories;
        /// <summary>
        /// There are no comments for Levels in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Level> Levels
        {
            get
            {
                if ((this._Levels == null))
                {
                    this._Levels = base.CreateQuery<Level>("Levels");
                }
                return this._Levels;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Level> _Levels;
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Session> Sessions
        {
            get
            {
                if ((this._Sessions == null))
                {
                    this._Sessions = base.CreateQuery<Session>("Sessions");
                }
                return this._Sessions;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Session> _Sessions;
        /// <summary>
        /// There are no comments for SessionTypes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SessionType> SessionTypes
        {
            get
            {
                if ((this._SessionTypes == null))
                {
                    this._SessionTypes = base.CreateQuery<SessionType>("SessionTypes");
                }
                return this._SessionTypes;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SessionType> _SessionTypes;
        /// <summary>
        /// There are no comments for Speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Speaker> Speakers
        {
            get
            {
                if ((this._Speakers == null))
                {
                    this._Speakers = base.CreateQuery<Speaker>("Speakers");
                }
                return this._Speakers;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Speaker> _Speakers;
        /// <summary>
        /// There are no comments for Tags in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Tag> Tags
        {
            get
            {
                if ((this._Tags == null))
                {
                    this._Tags = base.CreateQuery<Tag>("Tags");
                }
                return this._Tags;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Tag> _Tags;
        /// <summary>
        /// There are no comments for Tracks in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Track> Tracks
        {
            get
            {
                if ((this._Tracks == null))
                {
                    this._Tracks = base.CreateQuery<Track>("Tracks");
                }
                return this._Tracks;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Track> _Tracks;
        /// <summary>
        /// There are no comments for AudienceCategories in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAudienceCategories(AudienceCategory audienceCategory)
        {
            base.AddObject("AudienceCategories", audienceCategory);
        }
        /// <summary>
        /// There are no comments for Levels in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToLevels(Level level)
        {
            base.AddObject("Levels", level);
        }
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSessions(Session session)
        {
            base.AddObject("Sessions", session);
        }
        /// <summary>
        /// There are no comments for SessionTypes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSessionTypes(SessionType sessionType)
        {
            base.AddObject("SessionTypes", sessionType);
        }
        /// <summary>
        /// There are no comments for Speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSpeakers(Speaker speaker)
        {
            base.AddObject("Speakers", speaker);
        }
        /// <summary>
        /// There are no comments for Tags in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTags(Tag tag)
        {
            base.AddObject("Tags", tag);
        }
        /// <summary>
        /// There are no comments for Tracks in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTracks(Track track)
        {
            base.AddObject("Tracks", track);
        }
    }
    /// <summary>
    /// There are no comments for ODataTEModel.AudienceCategory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AudienceCategoryID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("AudienceCategories")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("AudienceCategoryID")]
    public partial class AudienceCategory : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new AudienceCategory object.
        /// </summary>
        /// <param name="audienceCategoryID">Initial value of AudienceCategoryID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static AudienceCategory CreateAudienceCategory(int audienceCategoryID)
        {
            AudienceCategory audienceCategory = new AudienceCategory();
            audienceCategory.AudienceCategoryID = audienceCategoryID;
            return audienceCategory;
        }
        /// <summary>
        /// There are no comments for Property AudienceCategoryID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AudienceCategoryID
        {
            get
            {
                return this._AudienceCategoryID;
            }
            set
            {
                this.OnAudienceCategoryIDChanging(value);
                this._AudienceCategoryID = value;
                this.OnAudienceCategoryIDChanged();
                this.OnPropertyChanged("AudienceCategoryID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AudienceCategoryID;
        partial void OnAudienceCategoryIDChanging(int value);
        partial void OnAudienceCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Session> Sessions
        {
            get
            {
                return this._Sessions;
            }
            set
            {
                this._Sessions = value;
                this.OnPropertyChanged("Sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Session> _Sessions = new global::System.Data.Services.Client.DataServiceCollection<Session>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ODataTEModel.Level in the schema.
    /// </summary>
    /// <KeyProperties>
    /// LevelID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Levels")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("LevelID")]
    public partial class Level : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Level object.
        /// </summary>
        /// <param name="levelID">Initial value of LevelID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Level CreateLevel(int levelID)
        {
            Level level = new Level();
            level.LevelID = levelID;
            return level;
        }
        /// <summary>
        /// There are no comments for Property LevelID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int LevelID
        {
            get
            {
                return this._LevelID;
            }
            set
            {
                this.OnLevelIDChanging(value);
                this._LevelID = value;
                this.OnLevelIDChanged();
                this.OnPropertyChanged("LevelID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _LevelID;
        partial void OnLevelIDChanging(int value);
        partial void OnLevelIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Session> Sessions
        {
            get
            {
                return this._Sessions;
            }
            set
            {
                this._Sessions = value;
                this.OnPropertyChanged("Sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Session> _Sessions = new global::System.Data.Services.Client.DataServiceCollection<Session>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ODataTEModel.Session in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SessionID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Sessions")]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("Title", System.Data.Services.Common.SyndicationItemProperty.Title, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("Abstract", System.Data.Services.Common.SyndicationItemProperty.Summary, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("ModifiedDate", System.Data.Services.Common.SyndicationItemProperty.Updated, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SessionID")]
    public partial class Session : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Session object.
        /// </summary>
        /// <param name="sessionID">Initial value of SessionID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Session CreateSession(int sessionID)
        {
            Session session = new Session();
            session.SessionID = sessionID;
            return session;
        }
        /// <summary>
        /// There are no comments for Property SessionID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SessionID
        {
            get
            {
                return this._SessionID;
            }
            set
            {
                this.OnSessionIDChanging(value);
                this._SessionID = value;
                this.OnSessionIDChanged();
                this.OnPropertyChanged("SessionID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SessionID;
        partial void OnSessionIDChanging(int value);
        partial void OnSessionIDChanged();
        /// <summary>
        /// There are no comments for Property TID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TID
        {
            get
            {
                return this._TID;
            }
            set
            {
                this.OnTIDChanging(value);
                this._TID = value;
                this.OnTIDChanged();
                this.OnPropertyChanged("TID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TID;
        partial void OnTIDChanging(string value);
        partial void OnTIDChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Abstract in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Abstract
        {
            get
            {
                return this._Abstract;
            }
            set
            {
                this.OnAbstractChanging(value);
                this._Abstract = value;
                this.OnAbstractChanged();
                this.OnPropertyChanged("Abstract");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Abstract;
        partial void OnAbstractChanging(string value);
        partial void OnAbstractChanged();
        /// <summary>
        /// There are no comments for Property Room in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Room
        {
            get
            {
                return this._Room;
            }
            set
            {
                this.OnRoomChanging(value);
                this._Room = value;
                this.OnRoomChanged();
                this.OnPropertyChanged("Room");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Room;
        partial void OnRoomChanging(string value);
        partial void OnRoomChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property StartTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return this._StartTime;
            }
            set
            {
                this.OnStartTimeChanging(value);
                this._StartTime = value;
                this.OnStartTimeChanged();
                this.OnPropertyChanged("StartTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
        /// <summary>
        /// There are no comments for Property EndTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return this._EndTime;
            }
            set
            {
                this.OnEndTimeChanging(value);
                this._EndTime = value;
                this.OnEndTimeChanged();
                this.OnPropertyChanged("EndTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
                this.OnPropertyChanged("ModifiedDate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Level in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Level Level
        {
            get
            {
                return this._Level;
            }
            set
            {
                this._Level = value;
                this.OnPropertyChanged("Level");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Level _Level;
        /// <summary>
        /// There are no comments for SessionType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SessionType SessionType
        {
            get
            {
                return this._SessionType;
            }
            set
            {
                this._SessionType = value;
                this.OnPropertyChanged("SessionType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private SessionType _SessionType;
        /// <summary>
        /// There are no comments for Track in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Track Track
        {
            get
            {
                return this._Track;
            }
            set
            {
                this._Track = value;
                this.OnPropertyChanged("Track");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Track _Track;
        /// <summary>
        /// There are no comments for AudienceCategories in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<AudienceCategory> AudienceCategories
        {
            get
            {
                return this._AudienceCategories;
            }
            set
            {
                this._AudienceCategories = value;
                this.OnPropertyChanged("AudienceCategories");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<AudienceCategory> _AudienceCategories = new global::System.Data.Services.Client.DataServiceCollection<AudienceCategory>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Speaker> Speakers
        {
            get
            {
                return this._Speakers;
            }
            set
            {
                this._Speakers = value;
                this.OnPropertyChanged("Speakers");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Speaker> _Speakers = new global::System.Data.Services.Client.DataServiceCollection<Speaker>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Tags in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Tag> Tags
        {
            get
            {
                return this._Tags;
            }
            set
            {
                this._Tags = value;
                this.OnPropertyChanged("Tags");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Tag> _Tags = new global::System.Data.Services.Client.DataServiceCollection<Tag>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ODataTEModel.SessionType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SessionTypeID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SessionTypes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SessionTypeID")]
    public partial class SessionType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SessionType object.
        /// </summary>
        /// <param name="sessionTypeID">Initial value of SessionTypeID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SessionType CreateSessionType(int sessionTypeID)
        {
            SessionType sessionType = new SessionType();
            sessionType.SessionTypeID = sessionTypeID;
            return sessionType;
        }
        /// <summary>
        /// There are no comments for Property SessionTypeID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SessionTypeID
        {
            get
            {
                return this._SessionTypeID;
            }
            set
            {
                this.OnSessionTypeIDChanging(value);
                this._SessionTypeID = value;
                this.OnSessionTypeIDChanged();
                this.OnPropertyChanged("SessionTypeID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SessionTypeID;
        partial void OnSessionTypeIDChanging(int value);
        partial void OnSessionTypeIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Session> Sessions
        {
            get
            {
                return this._Sessions;
            }
            set
            {
                this._Sessions = value;
                this.OnPropertyChanged("Sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Session> _Sessions = new global::System.Data.Services.Client.DataServiceCollection<Session>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ODataTEModel.Speaker in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SpeakerID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Speakers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SpeakerID")]
    public partial class Speaker : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Speaker object.
        /// </summary>
        /// <param name="speakerID">Initial value of SpeakerID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Speaker CreateSpeaker(int speakerID)
        {
            Speaker speaker = new Speaker();
            speaker.SpeakerID = speakerID;
            return speaker;
        }
        /// <summary>
        /// There are no comments for Property SpeakerID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SpeakerID
        {
            get
            {
                return this._SpeakerID;
            }
            set
            {
                this.OnSpeakerIDChanging(value);
                this._SpeakerID = value;
                this.OnSpeakerIDChanged();
                this.OnPropertyChanged("SpeakerID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SpeakerID;
        partial void OnSpeakerIDChanging(int value);
        partial void OnSpeakerIDChanged();
        /// <summary>
        /// There are no comments for Property SpeakerFirstName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SpeakerFirstName
        {
            get
            {
                return this._SpeakerFirstName;
            }
            set
            {
                this.OnSpeakerFirstNameChanging(value);
                this._SpeakerFirstName = value;
                this.OnSpeakerFirstNameChanged();
                this.OnPropertyChanged("SpeakerFirstName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SpeakerFirstName;
        partial void OnSpeakerFirstNameChanging(string value);
        partial void OnSpeakerFirstNameChanged();
        /// <summary>
        /// There are no comments for Property SpeakerLastName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SpeakerLastName
        {
            get
            {
                return this._SpeakerLastName;
            }
            set
            {
                this.OnSpeakerLastNameChanging(value);
                this._SpeakerLastName = value;
                this.OnSpeakerLastNameChanged();
                this.OnPropertyChanged("SpeakerLastName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SpeakerLastName;
        partial void OnSpeakerLastNameChanging(string value);
        partial void OnSpeakerLastNameChanged();
        /// <summary>
        /// There are no comments for Property LargeImage in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LargeImage
        {
            get
            {
                return this._LargeImage;
            }
            set
            {
                this.OnLargeImageChanging(value);
                this._LargeImage = value;
                this.OnLargeImageChanged();
                this.OnPropertyChanged("LargeImage");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LargeImage;
        partial void OnLargeImageChanging(string value);
        partial void OnLargeImageChanged();
        /// <summary>
        /// There are no comments for Property SmallImage in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SmallImage
        {
            get
            {
                return this._SmallImage;
            }
            set
            {
                this.OnSmallImageChanging(value);
                this._SmallImage = value;
                this.OnSmallImageChanged();
                this.OnPropertyChanged("SmallImage");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SmallImage;
        partial void OnSmallImageChanging(string value);
        partial void OnSmallImageChanged();
        /// <summary>
        /// There are no comments for Property Twitter in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Twitter
        {
            get
            {
                return this._Twitter;
            }
            set
            {
                this.OnTwitterChanging(value);
                this._Twitter = value;
                this.OnTwitterChanged();
                this.OnPropertyChanged("Twitter");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Twitter;
        partial void OnTwitterChanging(string value);
        partial void OnTwitterChanged();
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Session> Sessions
        {
            get
            {
                return this._Sessions;
            }
            set
            {
                this._Sessions = value;
                this.OnPropertyChanged("Sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Session> _Sessions = new global::System.Data.Services.Client.DataServiceCollection<Session>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ODataTEModel.Tag in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TagID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Tags")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("TagID")]
    public partial class Tag : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="tagID">Initial value of TagID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Tag CreateTag(int tagID)
        {
            Tag tag = new Tag();
            tag.TagID = tagID;
            return tag;
        }
        /// <summary>
        /// There are no comments for Property TagID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TagID
        {
            get
            {
                return this._TagID;
            }
            set
            {
                this.OnTagIDChanging(value);
                this._TagID = value;
                this.OnTagIDChanged();
                this.OnPropertyChanged("TagID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TagID;
        partial void OnTagIDChanging(int value);
        partial void OnTagIDChanged();
        /// <summary>
        /// There are no comments for Property TagName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TagName
        {
            get
            {
                return this._TagName;
            }
            set
            {
                this.OnTagNameChanging(value);
                this._TagName = value;
                this.OnTagNameChanged();
                this.OnPropertyChanged("TagName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TagName;
        partial void OnTagNameChanging(string value);
        partial void OnTagNameChanged();
        /// <summary>
        /// There are no comments for Tag1 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Tag> Tag1
        {
            get
            {
                return this._Tag1;
            }
            set
            {
                this._Tag1 = value;
                this.OnPropertyChanged("Tag1");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Tag> _Tag1 = new global::System.Data.Services.Client.DataServiceCollection<Tag>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Tag2 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Tag Tag2
        {
            get
            {
                return this._Tag2;
            }
            set
            {
                this._Tag2 = value;
                this.OnPropertyChanged("Tag2");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Tag _Tag2;
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Session> Sessions
        {
            get
            {
                return this._Sessions;
            }
            set
            {
                this._Sessions = value;
                this.OnPropertyChanged("Sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Session> _Sessions = new global::System.Data.Services.Client.DataServiceCollection<Session>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ODataTEModel.Track in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TrackID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Tracks")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("TrackID")]
    public partial class Track : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Track object.
        /// </summary>
        /// <param name="trackID">Initial value of TrackID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Track CreateTrack(int trackID)
        {
            Track track = new Track();
            track.TrackID = trackID;
            return track;
        }
        /// <summary>
        /// There are no comments for Property TrackID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TrackID
        {
            get
            {
                return this._TrackID;
            }
            set
            {
                this.OnTrackIDChanging(value);
                this._TrackID = value;
                this.OnTrackIDChanged();
                this.OnPropertyChanged("TrackID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TrackID;
        partial void OnTrackIDChanging(int value);
        partial void OnTrackIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Session> Sessions
        {
            get
            {
                return this._Sessions;
            }
            set
            {
                this._Sessions = value;
                this.OnPropertyChanged("Sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Session> _Sessions = new global::System.Data.Services.Client.DataServiceCollection<Session>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
